"""Pydantic data models for SolanaJupiterBot."""

from __future__ import annotations

from datetime import UTC, datetime
from enum import StrEnum
from typing import Any

from pydantic import BaseModel, Field


class TradeSide(StrEnum):
    """Trade side enumeration."""

    BUY = "buy"
    SELL = "sell"


class TradeStatus(StrEnum):
    """Trade status enumeration."""

    PENDING = "pending"
    EXECUTED = "executed"
    FAILED = "failed"
    CANCELLED = "cancelled"


class StrategyName(StrEnum):
    """Strategy name enumeration."""

    COPY_TRADING = "copy_trading"
    HOT_TRADING = "hot_trading"
    GEM_DETECTOR = "gem_detector"
    ARBITRAGE = "arbitrage"


class TokenInfo(BaseModel):
    """Token metadata information."""

    address: str
    symbol: str = ""
    name: str = ""
    decimals: int = 9
    supply: float = 0.0
    holder_count: int = 0
    created_at: datetime | None = None
    price_usd: float = 0.0
    liquidity_usd: float = 0.0
    market_cap_usd: float = 0.0


class TradeSignal(BaseModel):
    """Signal generated by a strategy engine."""

    strategy: StrategyName
    token_address: str
    token_symbol: str = ""
    side: TradeSide
    amount_usd: float
    confidence: float = Field(default=0.0, ge=0.0, le=1.0)
    reason: str = ""
    metadata: dict[str, Any] = Field(default_factory=dict)
    timestamp: datetime = Field(default_factory=lambda: datetime.now(UTC))


class TradeRecord(BaseModel):
    """Completed trade record."""

    id: str = ""
    strategy: StrategyName
    token_address: str
    token_symbol: str = ""
    side: TradeSide
    amount_usd: float
    amount_token: float = 0.0
    price: float = 0.0
    pnl: float = 0.0
    fees: float = 0.0
    slippage_bps: int = 0
    tx_signature: str = ""
    status: TradeStatus = TradeStatus.PENDING
    timestamp: datetime = Field(default_factory=lambda: datetime.now(UTC))
    execution_time_ms: float = 0.0


class ArbitrageOpportunity(BaseModel):
    """Detected arbitrage opportunity."""

    id: str = ""
    input_mint: str
    output_mint: str
    route_buy: str = ""
    route_sell: str = ""
    buy_amount: float = 0.0
    expected_output_buy: float = 0.0
    expected_output_sell: float = 0.0
    expected_profit_pct: float = 0.0
    expected_profit_usd: float = 0.0
    actual_profit_usd: float | None = None
    status: TradeStatus = TradeStatus.PENDING
    timestamp: datetime = Field(default_factory=lambda: datetime.now(UTC))


class RiskScore(BaseModel):
    """Risk assessment score for a token."""

    token_address: str
    score: int = Field(default=100, ge=0, le=100)
    checks: dict[str, Any] = Field(default_factory=dict)
    is_safe: bool = False
    timestamp: datetime = Field(default_factory=lambda: datetime.now(UTC))


class PortfolioSnapshot(BaseModel):
    """Snapshot of current portfolio state."""

    balance_usd: float = 0.0
    equity_usd: float = 0.0
    daily_pnl: float = 0.0
    weekly_pnl: float = 0.0
    total_pnl: float = 0.0
    open_positions: int = 0
    win_count: int = 0
    loss_count: int = 0
    updated_at: datetime = Field(default_factory=lambda: datetime.now(UTC))

    @property
    def win_rate(self) -> float:
        """Calculate win rate percentage."""
        total = self.win_count + self.loss_count
        if total == 0:
            return 0.0
        return self.win_count / total
